version: "3.9"

services:
  toxic-ml:
    build: .
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - 127.0.0.1:5000:5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
